### ISSUE TITLE
Parity with Carpentries callout styles?

### ISSUE THREAD

**Issue by smangham** [OxfordRSE/gutenberg#142]
I'm just porting a bunch of Carpentries Classic-format material to Gutenberg, and it makes quite heavy use of the range of callout formats like "Discussion", "Key Points", "Warning" and "Checklist", that don't exist in Gutenberg (beyond the basic `::::callout`).

Is this feature gap an intentional pedagogical/design decision? If not, it would be helpful for ease of porting if the callout styles could be mirrored. It'd really help us keep material in sync between the two so it doesn't get stranded/diverge.

(At some point I'd like to see what Carpentries Sandpaper format looks like and if it's going to be easier to translate to Gutenberg, as an automated process would _really_ help)

**Comment by martinjrobins** [comment]
It was intentional. I was always reluctant to deviate from plain markdown and didn't want to create much "bespoke" formatting. 

For "Discussion", is this like a "Challenge" without a solution?
For "Key Points", I normally just had a header with a list of key points at the end of each page of material
For "Warning", happy to discus this one because it actually could be useful to highlight warnings or dangers
For "Checklist", github markdown already has one of these (we use github markdown). You could stick it in a Challenge if it is a checklist for the students to do.

```
- [ ] incomplete task
- [x] completed task
```

**Comment by smangham** [comment]
That makes sense! Discussion as Challenge without solution is a good fit. Key Points callouts are usually used in-line to emphasise important points after they've been introduced, but again a Challenge without a Solution where you just start the title with '**⭐Key Point:**' is a good enough equivalent - the difference in Carpentries markdown is just the icon and background colour of the box I guess, and the background colour isn't really that important. GFM can cope with emoji, so just using them instead of having icons set by the CSS is probably good enough. Then you can get Warning with a Challenge with '**⚠️ Warning:**' in the title too. It's not *standardised*, per se, but the types are standardised at the Carpentries level so it's not like you'd get a mess of self-invented types leading to inconsistent lessons.

I guess the question this raises is if there's any implications to having a Gutenberg-format lesson full of non-Challenge Challenges and whether just doing this all via Callouts is better, but the header bar for Challenges really makes them stand out from the bulk text - callouts feel more appropriate for continuations of the material.

**Comment by alasdairwilson** [comment]
As you are disussing: by adding a callouttype to the callout directive we can make any change we want to in the css: I mocked up an example:

![image](https://github.com/OxfordRSE/gutenberg/assets/60351846/57da2a4e-2ac2-4a91-bc39-6d2292d1d7f3)

Which is inserted by:
```
::::callout{calloutClass="warning"}
## This is a title
This is a callout
::::
```
And the rest handled in the markdown, it allows us to support any arbitrary number of callout stylings

Is this something we want to pursue?

**Comment by martinjrobins** [comment]
Can we generalise this a bit? Something like:

```
:::callout{title="⚠️ Warning: This is a title" color="red"}
This is a callout
:::
```

@smangham mentioned that the callouts don't stand out due to lack of header bar, could add this for callouts and put the title there? Background of the header is the color chosen?

**Comment by alasdairwilson** [comment]
We definitely could have it control the color specifically my reasoning for wanting it to be more of a "class" of callout though is keep the same type of message consistent in appearance. If a warning will always look the same it makes writing the markdown easy since you insert a "warning" rather than a callout of a certain color (which we would have to either be defining anyway rather than using arbitrary colors or we need to be using tailwind colors and we lose control of light/dark theming) and it makes it easy for students to recognise the type of information that is going to be presented to them in each type of callout.

As for the actual visual style, that mockup was kind of based on the look of github markdown callouts:

> [!WARNING]
> This is a warning

We could give them coloured headings so they look something like:

![image](https://github.com/OxfordRSE/gutenberg/assets/60351846/541ac2a1-005a-45e4-8de0-81ac462eca0f)

**Comment by martinjrobins** [comment]
ok, lets go with the universal warning look. If we can leave the title up to the markdown that would be good, so that looking at the markdown directly gives you the same information as looking at the rendered page.

**Comment by alasdairwilson** [comment]
Ignore the colors which are a little ugly but instead the idea behind the layout, with block color

![image](https://github.com/OxfordRSE/gutenberg/assets/60351846/cbceea55-00c7-43d5-bee4-beacd5bbe25f)

And without:

![image](https://github.com/OxfordRSE/gutenberg/assets/60351846/8c755afe-d166-4309-8670-3e4aac5c20c0)

both are placed in markdown with:

```
::::callout{calloutClass="warning"}
This is a callout
::::
```

**Comment by martinjrobins** [comment]
I like the one without I think, less glaring on the eyes.

**Comment by alasdairwilson** [comment]
I agree, the color choice for the block header could be improved but I think it will still be a bit much, the other version is much cleaner.

**Comment by alasdairwilson** [comment]
@smangham 

We added "variants" to callouts in #156:

They look like:

<img width="751" alt="image" src="https://github.com/OxfordRSE/gutenberg/assets/60351846/38403f06-3ab8-45b3-ad19-7342f3aa8892">

the syntax to use one is:

```
::::callout{variant="variant"}
```

And variants are just the titles you can see in that image with no space (e.g. variant=keypoints)

It is not difficult to tweak the selection if you don't think it satisfies what you need.

**Comment by smangham** [comment]
Thank you - they look great!
