### ISSUE TITLE
Possibility to link to subsection?

### ISSUE THREAD

**Issue by eirini-zormpa** [OxfordRSE/gutenberg#192]
This is minor, but at the moment, it doesn't seem possible to link directly to a specific subsection of a page. For example, this link which was copied from the search (https://train.oxrse.uk/material/HPCu/technology_and_tooling/testing/scaling_up#Parameterising-Our-Unit-Tests) seems like it should take one directly to the *Parameterising our Unit Tests* section, but it actually only goes to the top of the page. As some of these lessons are pretty long, it would be useful to be able to link directly to a subsection.

**Comment by alasdairwilson** [comment]
Yeah! #22 provides anchor links for challenges but there are no others They were just added to the search prematurely until a solution was figured out which in retrospect has caused unnecessary confusion here.

See also #168 

it would be nice if we could link to specific paragraphs but I don't have a method in mind (another button like the comment button with a copy link perhaps). I think I shelves it because I hadn't decided if there was a better way to chop up the material rather than by subsection heading prior to vectorising it for the search!
