### ISSUE TITLE
executable code blocks

### ISSUE THREAD

**Issue by martinjrobins** [OxfordRSE/gutenberg#198]
It would be good to have the ability to modify / execute / compile code blocks. This would help students to tweak existing examples to get a better picture of what the code does, and also allow gutenberg to check that all the code blocks compile / run without errors on a deployment

**Comment by martinjrobins** [comment]
For the python code blocks I think pyiodide would be an easy solution to this. Here is an example of using this in react:

https://github.com/xhluca/react-pyodide-template

**Comment by mjaquiery** [comment]
@jackleland and I reckon we can cobble something together on this. The languages we want to serve are:
- Python
- C++
- Rust
- Bash
- (TypeScript/JavaScript)

We want to use pre-existing solutions, however many are necessary, and will prefer self-hosted ones over remote API ones.

**Comment by mjaquiery** [comment]
Following discussion with @alasdairwilson, @fcooper8472, @jackleland, @alexallmont:
- It's not clear that we actually _want_ students to be able to execute code in the browser - it may prevent them learning how to use stuff themselves
- Interpreted languages (Python/R) are much easier to do than compiled ones (C++/Rust)
- Preserving state is a tricky problem - hidden code lines are difficult for course authors, difficult for students to see. Otherwise determining appropriate state is hard
- @alexallmont is working on a template devcontainer setup for VSCode that course authors could use to allow students to follow course material on their own local system. Would allow access to system configuration information while not making things intimidating for new learners of a language.
- @alasdairwilson mentioned the possibility of automatically parsing Python courses into downloadable Jupyter code books.

This issue is being closed because the overall conclusion is that executable code blocks will not serve students' learning needs. 

Instead, we will provide pre-configured computational environments for course authors to identify in course metadata. Those environments will be GitHub templates, and can be customised if necessary. Course authors can create a repository and link to it in the metadata to identify it as the course execution environment repository. That repository can be cloned into VSCode or opened in GitHub Codespaces by the students.
We'll write a CI that will attach to the course material that will pursue the course execution environment to its target repository, spin up the relevant devcontainer environment, and step through code blocks one by one. This will identify errors, but not differences between output and expected output.
