### ISSUE TITLE
Backwards/forwards navigation between episodes

### ISSUE THREAD

**Issue by steve-crouch** [OxfordRSE/gutenberg#60]
Consider adding backwards and forwards navigation icons (perhaps at the bottom or top of the episode content pages) so learners and instructors can progress to previous and next episodes more quickly.

**Comment by martinjrobins** [comment]
The material is arranged in a graph rather than a linear stream (although a lot of courses do implement a linear stream). I've got around this by enforcing events to include course material in a linear stream, so that when you have selected a particular event, you get forward/backwards buttons guiding you forward and backwards through the material. 

Give this a try on the upcoming DTC course and see if you think this works

**Comment by steve-crouch** [comment]
As discussed, this sounds great - will test drive at the next DTC course.
